# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ThinIce' do

pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :tag => 'v2.3.3'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'YLProgressBar'

end

